3.3
inworld-ai/inworld-unity-core pull request #28
Opened 2024-03-12 00:58 UTC by Juniverse

Main Features:
1. Optimized Auto Reconnection, reducecd connection time.
2. Use tarball to replace github ref.

2024-03-14 21:53 UTC, mattkwilson requested changes
Good work!

Some notable points:

- Creating lots of new lists (e.g. `new List<string>{brainName}`) in the new API is going to create lots of garbage
- Push-to-talk needs a revamp, ManualAudioHandling in CharacterHandler is no longer utilized, I noticed when testing audio is still recorded when the PTT button is not held down

2024-03-14 21:53 UTC, mattkwilson commented on Runtime/Scripts/UI/BubblePanel.cs
> +            DestroyImmediate(elementToDestroy);
Is DestroyImmediate necessary here? If we need to wait for the object to be destroyed before UpdateContent we should use an enumerator.

2024-03-14 22:09 UTC, Juniverse commented on Runtime/Scripts/Data/Entities/InworldCharacterData.cs
> +        /// This function is used to rename to fullName. Somehow the current result from new method is naming like aaa__bbb
Mikhail Fixed this bug, no need to call this func now.

2024-03-14 22:09 UTC, Juniverse commented on Runtime/Scripts/Data/Packets/RelationPacket.cs
>          public string Relation => debugInfo.relation.relationState.GetUpdate(debugInfo.relation.relationUpdate);
That's the format of the data returned, the field has to be named as `debugInfo`

2024-03-14 22:10 UTC, Juniverse commented on Runtime/Scripts/Interaction/InworldInteraction.cs
> +                    if (InworldController.Audio.SampleMode != MicSampleMode.TURN_BASED || !InworldController.Audio.CurrentPlayingPlayer || !InworldController.Audio.CurrentPlayingPlayer.isPlaying)
Use `CurrentPlayingAudioSource`

2024-03-14 23:33 UTC, mattkwilson approved these changes

2024-03-15 00:01 UTC, Juniverse commented on Runtime/Scripts/UI/BubblePanel.cs
> +            DestroyImmediate(elementToDestroy);
change back to Destroy()

2024-03-15 00:07 UTC, merged