Update comments for doc
inworld-ai/inworld-unity-core pull request #37
Opened 2024-03-28 21:30 UTC by Juniverse

2024-03-28 22:14 UTC, mattkwilson requested changes

2024-03-28 22:14 UTC, mattkwilson commented on Runtime/Scripts/InworldClient.cs
> +        /// Unload curren scene. Make sure to be called before loading another scene.
Spelling:  *current

2024-03-28 22:14 UTC, mattkwilson commented on Runtime/Scripts/CharacterHandler.cs
> +        ///     Gets the list of all the current character's brain name in the conversation.
Remove tab to stay consistent.

2024-03-29 18:43 UTC, RobHCo approved these changes

2024-04-01 22:04 UTC, merged