Audio Update Hotfix
inworld-ai/inworld-unity-core pull request #46
Opened 2024-05-09 23:59 UTC by Juniverse

1. Fixed a bug that not able to talk with multi characters.
2. Used SNR (dB) to better detect voice (eliminate noices better)

2024-05-10 23:02 UTC, mattkwilson requested changes

2024-05-10 23:02 UTC, mattkwilson commented on Runtime/Scripts/AudioCapture.cs
> +            });
This function is going to create garbage. Considering SendAudio is called frequently we should avoid creating new lists if we can help it. Instead we should have a list or lists that we reuse by just updating the element(s).

2024-05-13 20:02 UTC, Juniverse commented on Runtime/Scripts/AudioCapture.cs
> +            });
Let's implement in the 3.4

2024-05-13 22:28 UTC, mattkwilson requested changes

2024-05-13 22:28 UTC, mattkwilson commented on Runtime/Scripts/AudioCapture.cs
> +        protected bool m_NeedCalibrate = true;
This field is unnecessary as discussed.

2024-05-14 21:01 UTC, mattkwilson approved these changes

2024-05-14 21:14 UTC, mattkwilson approved these changes

2024-05-14 21:20 UTC, merged