Updated AEC and VAD features
inworld-ai/inworld-unity-core pull request #72
Opened 2024-08-29 19:21 UTC by Juniverse

If VAD is enabled. When player speaking detected, we'll pause the audio playing. So that the AEC quality would be improved.

Also added back the cache list for cancelled items.

INTG-1997, INTG-1980, INTG-1967, INTG-1908

2024-08-30 22:43 UTC, mattkwilson requested changes
Please see comments.

2024-08-30 22:43 UTC, mattkwilson commented on Runtime/Scripts/Interaction/InworldInteraction.cs
> +        public AudioSource PlaybackSource => m_PlaybackSource;
This should probably only exist within InworldAudioInteraction.

2024-08-30 22:43 UTC, mattkwilson commented on Runtime/Scripts/Interaction/InworldInteraction.cs
`m_AnimFactor` is no longer used and can be removed

2024-08-30 22:43 UTC, mattkwilson commented on Runtime/Scripts/Interaction/InworldAudioInteraction.cs
> +using System.Linq;
Not necessary

2024-08-30 22:43 UTC, mattkwilson commented on Runtime/Scripts/Interaction/InworldAudioInteraction.cs
> +                yield return new WaitUntil(() => m_PlaybackSource.clip == null || m_PlaybackSource.time >= m_PlaybackSource.clip.length - Time.fixedUnscaledDeltaTime);
Why subtract by `Time.fixedUnscaledDeltaTime`?

2024-09-05 20:51 UTC, Juniverse commented on Runtime/Scripts/Interaction/InworldAudioInteraction.cs
> +                yield return new WaitUntil(() => m_PlaybackSource.clip == null || m_PlaybackSource.time >= m_PlaybackSource.clip.length - Time.fixedUnscaledDeltaTime);
The audio's playing is in a separate thread other than Unity's game lifecycle. Which means, there is a highly chance that in the last frame, the `m_PlaybackSource.time` is smaller than  `m_PlaybackSource.clip.length`, (the difference is less than deltaTime), but in the next frame, it stopped playing and return 0.

2024-09-09 21:31 UTC, closed without merging